name: Commandments
main: uk.co.oliwali.Commandments.Commandments
author: oliverw92
version: 1.0.0
softdepend: [Permissions,PermissionsEx,GroupManager]
description: Moses ain't got nothing on this plugin
